### ISSUE TITLE
Handle redesignated/duplicate 16 CFR 460.23

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#245] opened 2020-06-16 00:04 UTC
Title 16 section 460.23 was updated on 2020-05-14 with a number of tax related changes resulting in a duplicate 460.23.

They appear to be due to this change to Title 26:
https://www.federalregister.gov/documents/2019/05/13/2019-09552/recognition-and-deferral-of-section-987-gain-or-loss

```diff
-<CITA TYPE="N">[70 FR 31274, May 31, 2005]
+<CITA TYPE="N">[84 FR 20788, May 13, 2019]
```

It should probably be the updated, smaller content, but the FR Doc doesn't address this title directly and this issue of two 460.23 is still present in the latest source xml received_on `2020-06-02`

```diff
 <DIV8 N="§ 460.23" NODE="16:1.0.1.4.59.0.32.23" TYPE="SECTION">
+<HEAD>§ 460.23   Tax claims.</HEAD>
+<P>Do not say or imply that your product qualifies for a tax benefit unless it is true.
+</P>
+<CITA TYPE="N">[44 FR 50242, Aug. 27, 1979. Redesignated at 84 FR 20790, May 13, 2019]
+
+
+
+
+</CITA>
+</DIV8>
+
+
+<DIV8 N="§ 460.23" NODE="16:1.0.1.4.59.0.32.24" TYPE="SECTION">
 <HEAD>§ 460.23   Other laws, rules, and orders.</HEAD>
-<XREF ID="20190513" REFID="25">Link to an amendment published at 84 FR 20790, May 13, 2019.</XREF>
 <P>(a) If an outstanding FTC Cease and Desist Order applies to you but differs from the rules given here, you can petition to amend to order.
 </P>
 <P>(b) State and local laws and regulations that are inconsistent with, or frustrate the purposes of, the provisions of this regulation are preempted. However, a State or local government may petition the Commission, for good cause, to permit the enforcement of any part of a State or local law or regulation that would be preempted by this section.
 </P>
 <P>(c) The Commission's three-day cooling-off rule stays in force.
 </P>
-<CITA TYPE="N">[44 FR 50242, Aug. 27, 1979, as amended at 70 FR 31276, May 31, 2005]
+<CITA TYPE="N">[44 FR 50242, Aug. 27, 1979, as amended at 70 FR 31276, May 31, 2005. Redesignated at 84 FR 20790, May 13, 2019]
 
 
 </CITA>
 </DIV8>
```

whole diff: 

[diff_title_16_2020-04-22_2020-05-14.diff.txt](https://github.com/criticaljuncture/ecfr-xml-corrections/files/4783557/diff_title_16_2020-04-22_2020-05-14.diff.txt)

**Comment by peregrinator** [comment] 2020-11-21 00:21
Duplicate of #239.

**Closed as completed by peregrinator** 2020-11-21 00:21 UTC
Labels: OFR, support
